name: record_linux
description: Patched Linux implementation for record package.
version: 0.7.2
homepage: https://github.com/llfbandit/record/tree/master/record_linux

environment:
  sdk: ^3.3.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  record_platform_interface: ^1.0.2

flutter:
  plugin:
    implements: record
    platforms:
      linux:
        pluginClass: RecordLinuxPlugin
        dartPluginClass: RecordLinux
